apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-node-app.fullname" . }}
  labels:
    {{- include "my-node-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "my-node-app.selectorLabels" . | nindent 4 }}
