pipeline {
    agent any

    environment {
        IMAGE_NAME = "vikashsingh347/node-app"
        TAG = "v1"
        REGISTRY_CREDENTIALS = 'dockerhub-creds'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Vikash-Singh631/Home-Assignment.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'cd $(pwd)/Home-Assignment/node-app; docker build -t $IMAGE_NAME:$TAG .'
                }
            }
        }
        stage('Security Scan - Trivy') {
            steps {
                sh 'trivy image $IMAGE_NAME:$TAG || true'
            }
        }

        stage('Push to Docker Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: "$REGISTRY_CREDENTIALS", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $IMAGE_NAME:$TAG
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh '''
                        cd $(pwd)/Home-Assignment/node-app/chart;helm upgrade --install my-node-app ./my-node-app --set image.repository=$IMAGE_NAME,image.tag=$TAG
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }
        failure {
            echo 'Deployment Failed!'
        }
    }
}

